name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the form below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure connector with...
        2. Apply SMT transformation...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: The SMT should transform the record to...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Instead, the record was...
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Connector Configuration
      description: Your Kafka Connect connector configuration (remove sensitive information)
      placeholder: |
        {
          "name": "example-connector",
          "config": {
            "transforms": "extractAudit",
            "transforms.extractAudit.type": "..."
          }
        }
      render: yaml

  - type: textarea
    id: sample
    attributes:
      label: Sample Input/Output
      description: Sample input record and expected/actual output (if applicable)
      placeholder: |
        Input:
        {
          "op": "c",
          "after": {...}
        }
        
        Expected Output:
        {
          "operation": "INSERT",
          ...
        }
      render: json

  - type: textarea
    id: logs
    attributes:
      label: Logs/Error Messages
      description: Relevant log output or error messages
      placeholder: Paste logs or error messages here...
      render: shell

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Which version of the SMT are you using?
      options:
        - "2.0.1"
        - "2.0.0"
        - "Other (please specify)"
    validations:
      required: true

  - type: input
    id: kafka-version
    attributes:
      label: Kafka Connect Version
      description: Version of Kafka Connect you're using
      placeholder: e.g., 2.2.2-cp7, 3.5.0
    validations:
      required: true

  - type: input
    id: java-version
    attributes:
      label: Java Version
      description: Java version used
      placeholder: e.g., 1.8, 11, 17
    validations:
      required: true

  - type: dropdown
    id: database
    attributes:
      label: Source Database
      description: Which database are you using with Debezium?
      options:
        - "SQL Server"
        - "MySQL"
        - "PostgreSQL"
        - "Oracle"
        - "MongoDB"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Operating system, deployment environment, etc.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this bug has not been reported before
          required: true
        - label: I have included all relevant information above
          required: true

